### ISSUE TITLE
A communication error occurred while writing messages

### ISSUE THREAD

**Issue by awad1080** [xioTechnologies/NGIMU-Software-Public#3]
I have been connecting my NGIMU to the GUI to calibrate the values through the settings but an error occurs after the IMU establishes a connection, it crashes and stops displaying any msgs and I get this error 

/*
System.Exception: Could not send OSC packet. ---> System.IO.IOException: A device attached to the system is not functioning.

   at System.IO.Ports.InternalResources.WinIOError(Int32 errorCode, String str)
   at System.IO.Ports.SerialStream.EndWrite(IAsyncResult asyncResult)
   at System.IO.Ports.SerialStream.Write(Byte[] array, Int32 offset, Int32 count, Int32 timeout)
   at System.IO.Ports.SerialPort.Write(Byte[] buffer, Int32 offset, Int32 count)
   at NgimuApi.ConnectionImplementations.SerialConnectionImplementation.Send(OscPacket packet)
   at NgimuApi.Connection.Send(OscPacket packet)
   --- End of inner exception stack trace ---
   at NgimuApi.Connection.Send(OscPacket packet)
   at NgimuApi.CommunicationProcess.SendMessage(OscMessage message)

*/

the problem is shortly resolved by re-uploading the firmware. but the IMU keeps crashing... does anyone know what's the cause of this ? .. I've changed cables and used different computers but nothing works

**Comment by xioTechnologies** [comment]
Do you have this issue with the pre-compiled NGIMU GUI provided on the website or is the issue limited to your own compilation?

**Comment by awad1080** [comment]
this is with the pre-compiled NGIMU GUI
